source 'https://rubygems.org'
ruby '2.6.4'
# APP AND DB
gem "koala"
gem 'bootsnap', require: false
gem 'devise'
gem 'haml'
gem 'omniauth-facebook'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma'
gem 'rails', '6.0.2.1'
gem 'rails-i18n'
gem 'redis'
gem 'sidekiq'
gem 'sidekiq-failures', '~> 1.0'
gem 'simple_form'
gem 'webpacker'

group :development do
  gem 'bullet'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rubocop'
  gem 'rubocop-rails'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end
